version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart_home_api
    environment:
      DB_HOST: postgres_db
      DB_NAME: iot_data
      DB_USER: iot_user
      DB_PASS: iot_password
      MQTT_BROKER: mqtt-broker
      MQTT_PORT: 1883
    ports:
      - "8000:8000"
    depends_on:
      postgres_db:
        condition: service_healthy
      mqtt-broker:
        condition: service_started
    networks:
      - iot_network
    restart: unless-stopped

  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ../mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - iot_network
    restart: unless-stopped

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: iot_user
      POSTGRES_PASSWORD: iot_password
      POSTGRES_DB: iot_data
    ports:
      - "5432:5432"
    volumes:
      - ../data_storage/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - iot_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iot_user -d iot_data"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  iot_network:
    driver: bridge
